---
# Travis build file
language: php
sudo: false

matrix:
  include:
    - php: 5.6
    - php: hhvm
    - php: 7.0
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
# Remove xdebug as per https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer
  - if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer validate

install:
  - composer install --prefer-dist

script:
  - bin/test --no-fix
